# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
loader_version=0.17.2

# Mod Properties
mod_version=0.17.7+1.21.8-refabricated
maven_group=com.ncpbails
archives_base_name=cultural-delights

# Dependencies
fabric_version=0.133.0+1.21.8
fdrf_version = 1.21.8-3.2.4+refabricated
jei_version = 24.0.0.2
lithostitched_version = cBKQ7dDx
modmenu_version = 15.0.0