# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
loader_version=0.16.14

# Mod Properties
mod_version=0.17.7+1.21.5-refabricated
maven_group=com.ncpbails
archives_base_name=cultural-delights

# Dependencies
fabric_version=0.128.1+1.21.5
fdrf_version = 1.21.5-3.1.3+refabricated
jei_version = 21.3.2.22
lithostitched_version = 1.4.8
modmenu_version = 14.0.0-rc.2